// GatewayBridge.h
// Deep Tree Echo - OpenClaw Gateway Bridge
// IPC bridge between UE5 cognitive core and angelclaw's TypeScript gateway
// Copyright (c) 2026 Deep Tree Echo Project

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "OpenClawConfig.h"
#include "GatewayBridge.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnMessageReceived, const FOpenClawMessage&, Message);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnSessionStarted, const FString&, SessionID,
                                              EOpenClawChannel, Channel);

/**
 * UGatewayBridge
 *
 * IPC bridge between u9n's Unreal Engine cognitive core and angelclaw's
 * openclaw-gateway TypeScript server. Communication happens via WebSocket
 * using JSON-RPC protocol.
 *
 * The gateway handles:
 * - Multi-channel message routing (12+ platforms)
 * - Session lifecycle management (per-user/channel)
 * - Cognitive skill invocation
 * - Personality persistence across channels
 *
 * This bridge translates between UE5 component messages and the
 * gateway's JSON-RPC protocol, enabling the cognitive core to
 * interact with users across all supported platforms.
 */
UCLASS(ClassGroup = (DeepTreeEcho), meta = (BlueprintSpawnableComponent),
       DisplayName = "OpenClaw Gateway Bridge")
class DEEPTREEECHO_API UGatewayBridge : public UActorComponent
{
    GENERATED_BODY()

public:
    UGatewayBridge();

    virtual void BeginPlay() override;
    virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
    virtual void TickComponent(float DeltaTime, ELevelTick TickType,
                               FActorComponentTickFunction* ThisTickFunction) override;

    // --- Connection ---

    /** Connect to the openclaw-gateway WebSocket server */
    UFUNCTION(BlueprintCallable, Category = "Gateway")
    bool Connect();

    /** Disconnect from the gateway */
    UFUNCTION(BlueprintCallable, Category = "Gateway")
    void Disconnect();

    /** Check if connected to gateway */
    UFUNCTION(BlueprintPure, Category = "Gateway")
    bool IsConnected() const { return bConnected; }

    // --- Messaging ---

    /** Send a message to a specific channel/session */
    UFUNCTION(BlueprintCallable, Category = "Gateway")
    bool SendMessage(const FString& SessionID, EOpenClawChannel Channel,
                     const FString& Content);

    /** Send a cognitive response generated by the DTE system */
    UFUNCTION(BlueprintCallable, Category = "Gateway")
    bool SendCognitiveResponse(const FString& SessionID, const FString& Response,
                                float EmotionalValence = 0.0f);

    /** Broadcast to all active sessions on a specific channel */
    UFUNCTION(BlueprintCallable, Category = "Gateway")
    void BroadcastToChannel(EOpenClawChannel Channel, const FString& Content);

    // --- Session Management ---

    /** Get all active session IDs */
    UFUNCTION(BlueprintPure, Category = "Gateway")
    TArray<FString> GetActiveSessions() const;

    /** Get session count */
    UFUNCTION(BlueprintPure, Category = "Gateway")
    int32 GetActiveSessionCount() const { return ActiveSessions.Num(); }

    // --- Events ---

    /** Fired when a message is received from any channel */
    UPROPERTY(BlueprintAssignable, Category = "Gateway|Events")
    FOnMessageReceived OnMessageReceived;

    /** Fired when a new session starts */
    UPROPERTY(BlueprintAssignable, Category = "Gateway|Events")
    FOnSessionStarted OnSessionStarted;

protected:
    /** Gateway configuration */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gateway|Config")
    FOpenClawGatewayConfig Config;

    /** Auto-connect on BeginPlay */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gateway|Config")
    bool bAutoConnect = true;

    /** Reconnect interval on connection loss (seconds) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gateway|Config")
    float ReconnectInterval = 5.0f;

private:
    bool bConnected = false;
    TMap<FString, EOpenClawChannel> ActiveSessions;
    float ReconnectTimer = 0.0f;

    /** Process incoming JSON-RPC message from gateway */
    void ProcessIncomingMessage(const FString& JsonPayload);

    /** Serialize outgoing message to JSON-RPC format */
    FString SerializeToJsonRPC(const FString& Method, const FString& Params) const;
};
