#pragma once
// ═══════════════════════════════════════════════════════════════════════════
// IonDeviceUnit — Auto-generated by PE-to-NPU pipeline
// Source: ion.exe
// Generated: 2026-03-25T07:23:05Z
// ═══════════════════════════════════════════════════════════════════════════

#include "virtual-device.h"
#include <string>
#include <vector>
#include <cstdint>

namespace ggnucash::vdev {

// ═══ Register Layout ═══════════════════════════════════════════════════════
static constexpr uint64_t ION_BASE = 0x40002000;

// Control Block (0x000 - 0x03F)
static constexpr uint64_t REG_ION_CMD       = ION_BASE + 0x00;
static constexpr uint64_t REG_ION_STATUS    = ION_BASE + 0x04;
static constexpr uint64_t REG_ION_VERSION   = ION_BASE + 0x08;
static constexpr uint64_t REG_ION_FLAGS     = ION_BASE + 0x0C;
static constexpr uint64_t REG_ION_ERROR     = ION_BASE + 0x10;
static constexpr uint64_t REG_ION_DEBUG     = ION_BASE + 0x14;

// Telemetry Block (0x180 - 0x1BF)
static constexpr uint64_t REG_ION_DISPATCH_CNT = ION_BASE + 0x180;
static constexpr uint64_t REG_ION_CACHE_HITS   = ION_BASE + 0x184;
static constexpr uint64_t REG_ION_CACHE_MISS   = ION_BASE + 0x188;
static constexpr uint64_t REG_ION_LATENCY_NS   = ION_BASE + 0x18C;
static constexpr uint64_t REG_ION_ERROR_CNT    = ION_BASE + 0x190;
static constexpr uint64_t REG_ION_UPTIME_SEC   = ION_BASE + 0x194;

// Function Table (0x200+)
static constexpr uint64_t ION_FUNC_TABLE   = ION_BASE + 0x200;
static constexpr uint32_t ION_FUNC_COUNT   = 7299;

// ═══ Command Bits ══════════════════════════════════════════════════════════
enum IonDeviceUnitCmd : uint32_t {
    CMD_NOP        = 0x00000000,
    CMD_RESET      = 0x00000001,
    CMD_INIT       = 0x00000002,
    CMD_SHUTDOWN   = 0x00000004,
    CMD_SELF_TEST  = 0x00004000,
    CMD_SOFT_STOP  = 0x80000000,
};

// ═══ Status Bits ═══════════════════════════════════════════════════════════
enum IonDeviceUnitStatus : uint32_t {
    STATUS_IDLE    = 0x00000000,
    STATUS_BUSY    = 0x00000001,
    STATUS_INIT    = 0x00000002,
    STATUS_READY   = 0x00000010,
    STATUS_ERROR   = 0x00000080,
};

// ═══ Telemetry ═════════════════════════════════════════════════════════════
struct IonDeviceUnitTelemetry {
    uint64_t total_dispatches = 0;
    uint64_t cache_hits = 0;
    uint64_t cache_misses = 0;
    double   avg_latency_ns = 0.0;
    uint64_t error_count = 0;
    uint64_t uptime_seconds = 0;
};

// ═══ Entelechy Metadata ═══════════════════════════════════════════════════
struct IonDeviceUnitEntelechy {
    const char* source_binary = "ion.exe";
    const char* primary_api = "unknown";
    const char* primary_domain = "unknown";
    uint32_t    total_functions = 7299;
    uint32_t    export_count = 3359;
    uint32_t    import_count = 581;
    bool        has_cfg = true;
    bool        has_aslr = true;
    bool        has_dep = true;
};

// ═══ Device Driver ═════════════════════════════════════════════════════════
class IonDeviceUnit : public DeviceDriver {
public:
    bool load(VirtualPCB* pcb_) override;
    bool initialize() override;
    bool probe() override;
    bool remove() override;

    // Telemetry
    IonDeviceUnitTelemetry get_telemetry() const;
    IonDeviceUnitEntelechy get_entelechy() const;
    std::string get_status_string() const;
    std::string get_diagnostics() const;
    bool run_self_test();

private:
    VirtualPCB* pcb_ = nullptr;
    IonDeviceUnitTelemetry telemetry_;
    IonDeviceUnitEntelechy entelechy_;

    void write_reg32(uint64_t addr, uint32_t value);
    uint32_t read_reg32(uint64_t addr) const;
};

} // namespace ggnucash::vdev
