// Copyright Deep Tree Echo. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "AIController/AIController.h"
#include "Perception/AIPerceptionComponent.h"
#include "Core/DeepTreeEchoCore.h"
#include "DeepTreeEchoAIController.generated.h"

/**
 * Deep Tree Echo AI Controller
 *
 * Connects the Deep Tree Echo cognitive architecture (UDeepTreeEchoCore) to
 * Unreal Engine's AI framework.  On possession it finds or creates the pawn's
 * UDeepTreeEchoCore component, feeds perception data into the cognitive cycle
 * each tick, and translates cognitive outputs into movement and focus actions.
 *
 * Usage:
 *   1. Assign ADeepTreeEchoAIController as the AIControllerClass on your
 *      Character or Pawn blueprint.
 *   2. Ensure the pawn's actor has a UDeepTreeEchoCore component (it will be
 *      created automatically if absent).
 *   3. The controller drives the cognitive cycle at CognitiveTickRate Hz and
 *      converts salience outputs into navigation / focus commands.
 */
UCLASS(ClassGroup=(DeepTreeEcho), BlueprintType, Blueprintable)
class DEEPTREEECHOAVATAR_API ADeepTreeEchoAIController : public AAIController
{
    GENERATED_BODY()

public:
    ADeepTreeEchoAIController();

    // -----------------------------------------------------------------------
    // Configuration
    // -----------------------------------------------------------------------

    /** How many times per second the cognitive cycle is ticked (default: 10 Hz). */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "DeepTreeEcho|AI|Config",
              meta = (ClampMin = "1.0", ClampMax = "60.0"))
    float CognitiveTickRate = 10.0f;

    /** Minimum salience value required to trigger a movement action (0–1). */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "DeepTreeEcho|AI|Config",
              meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float MovementSalienceThreshold = 0.6f;

    /** Minimum salience value required to change focus target (0–1). */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "DeepTreeEcho|AI|Config",
              meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float FocusSalienceThreshold = 0.4f;

    /** Acceptance radius for MoveToActor navigation requests (cm). */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "DeepTreeEcho|AI|Config",
              meta = (ClampMin = "10.0", ClampMax = "500.0"))
    float NavigationAcceptanceRadius = 100.0f;

    /** Enable debug logging of per-tick cognitive→action mapping. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "DeepTreeEcho|AI|Config")
    bool bDebugLogging = false;

    // -----------------------------------------------------------------------
    // Runtime state (read-only from Blueprint)
    // -----------------------------------------------------------------------

    /** Cached reference to the pawn's cognitive core component. */
    UPROPERTY(BlueprintReadOnly, Category = "DeepTreeEcho|AI|State")
    UDeepTreeEchoCore* CognitiveCore = nullptr;

    /** Last perception-driven salience scores fed into the cognitive cycle. */
    UPROPERTY(BlueprintReadOnly, Category = "DeepTreeEcho|AI|State")
    TArray<float> LastSalienceVector;

    /** Last action output vector generated by the cognitive cycle. */
    UPROPERTY(BlueprintReadOnly, Category = "DeepTreeEcho|AI|State")
    TArray<float> LastActionVector;

    /** Actor currently targeted by movement (may be null). */
    UPROPERTY(BlueprintReadOnly, Category = "DeepTreeEcho|AI|State")
    AActor* CurrentMoveTarget = nullptr;

    // -----------------------------------------------------------------------
    // Blueprint-callable API
    // -----------------------------------------------------------------------

    /**
     * Manually inject a perception stimulus into the cognitive cycle.
     * @param SensoryData  Flat float vector (any modality).
     * @param Modality     Label string e.g. "Visual", "Auditory", "Threat".
     */
    UFUNCTION(BlueprintCallable, Category = "DeepTreeEcho|AI")
    void InjectPerceptionStimulus(const TArray<float>& SensoryData, const FString& Modality);

    /**
     * Override the current movement target.  Passing nullptr clears the target.
     */
    UFUNCTION(BlueprintCallable, Category = "DeepTreeEcho|AI")
    void SetMoveTarget(AActor* NewTarget);

    /** Force an immediate cognitive cycle tick regardless of tick rate. */
    UFUNCTION(BlueprintCallable, Category = "DeepTreeEcho|AI")
    void ForceCognitiveTick();

    /** Get the current cognitive mode string from the core. */
    UFUNCTION(BlueprintCallable, Category = "DeepTreeEcho|AI")
    FString GetCognitiveModeString() const;

    // -----------------------------------------------------------------------
    // Overrides
    // -----------------------------------------------------------------------

    virtual void OnPossess(APawn* InPawn) override;
    virtual void OnUnPossess() override;
    virtual void Tick(float DeltaTime) override;

protected:
    virtual void BeginPlay() override;

private:
    // -----------------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------------

    /** Find or create UDeepTreeEchoCore on the possessed pawn. */
    void AcquireCognitiveCore(APawn* InPawn);

    /** Gather perception stimuli from UAIPerceptionComponent and push to core. */
    void FeedPerceptionToCognition();

    /** Read action outputs from the core and apply movement/focus commands. */
    void ApplyCognitiveActionsToWorld(const TArray<float>& ActionVector);

    /** Tick accumulator — triggers cognition at CognitiveTickRate. */
    float CognitiveTickAccumulator = 0.0f;

    /** Cached reference to the perception component. */
    UAIPerceptionComponent* PerceptionComponent = nullptr;
};
