if(EXISTS "/home/runner/work/u9n/u9n/build_test/TensorLogicTests[1]_tests.cmake")
  include("/home/runner/work/u9n/u9n/build_test/TensorLogicTests[1]_tests.cmake")
else()
  add_test(TensorLogicTests_NOT_BUILT TensorLogicTests_NOT_BUILT)
endif()
